'use strict'

export TriangleGeometry from './triangle'
export CylinderGeometry from './cylinder'
export CapsuleGeometry from './capsule'
export SphereGeometry from './sphere'
export PlaneGeometry from './plane'
export TorusGeometry from './torus'
export BoxGeometry from './box'
export Geometry from './geometry'
