#ifndef GLSL_VARYING_VARIABLES
#define GLSL_VARYING_VARIABLES

#ifndef GLSL_VARYING_COLOR_VARIABLE
#define GLSL_VARYING_COLOR_VARIABLE vColor
#endif

#ifndef GLSL_VARYING_POSITION_VARIABLE
#define GLSL_VARYING_POSITION_VARIABLE vPosition
#endif

#ifndef GLSL_VARYING_LOCAL_POSITION_VARIABLE
#define GLSL_VARYING_LOCAL_POSITION_VARIABLE vLocalPosition
#endif

#ifndef GLSL_VARYING_NORMAL_VARIABLE
#define GLSL_VARYING_NORMAL_VARIABLE vNormal
#endif

#ifndef GLSL_VARYING_LOCAL_NORMAL_VARIABLE
#define GLSL_VARYING_LOCAL_NORMAL_VARIABLE vLocalNormal
#endif

#ifndef GLSL_VARYING_UV_VARIABLE
#define GLSL_VARYING_UV_VARIABLE vUv
#endif

#endif
