#ifndef GLSL_MESH_VERTEX_ATTRIBUTES
#define GLSL_MESH_VERTEX_ATTRIBUTES

#ifndef GLSL_MESH_VERTEX_ATTRIBUTES_NO_COLOR
#ifdef GLSL_MESH_VERTEX_ATTRIBUTES_HAVE_COLOR
#define GLSL_MESH_VERTEX_ATTRIBUTES_USE_COLOR
attribute vec4 color;
#endif
#endif

#endif
