#ifndef GLSL_MESH_VERTEX_ATTRIBUTES_UV
#define GLSL_MESH_VERTEX_ATTRIBUTES_UV

#ifndef GLSL_MESH_VERTEX_ATTRIBUTES_NO_UV
#ifdef GLSL_MESH_VERTEX_ATTRIBUTES_HAVE_UV
#define GLSL_MESH_VERTEX_ATTRIBUTES_USE_UV
attribute vec2 uv;
#endif
#endif

#endif
