#ifndef GLSL_TEXTURE_UNIFORMS
#define GLSL_TEXTURE_UNIFORMS

#include "./variables"

#ifdef GLSL_TEXTURE_2D
uniform sampler2D GLSL_TEXTURE_2D_SAMPLER_VARIABLE;
uniform vec2 GLSL_TEXTURE_2D_RESOLUTION_VARIABLE;
#endif

#ifdef GLSL_TEXTURE_CUBE
uniform samplerCube GLSL_TEXTURE_CUBE_SAMPLER_VARIABLE;
uniform vec2 GLSL_TEXTURE_CUBE_RESOLUTION_VARIABLE;
#endif

#endif
