#ifndef GLSL_TEXTURE_VARIABLES
#define GLSL_TEXTURE_VARIABLES

#ifndef GLSL_TEXTURE_2D_VARIABLE
#define GLSL_TEXTURE_2D_VARIABLE tex2d
#endif

#ifndef GLSL_TEXTURE_CUBE_VARIABLE
#define GLSL_TEXTURE_CUBE_VARIABLE texCube
#endif

#endif
