window.esdocSearchIndex = [
  [
    "axis3d/src/light/types.js~ambientlight",
    "variable/index.html#static-variable-AmbientLight",
    "<span>AmbientLight</span> <span class=\"search-result-import-path\">axis3d/src/light/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/ambient.js~ambientlightcommand",
    "class/src/light/ambient.js~AmbientLightCommand.html",
    "<span>AmbientLightCommand</span> <span class=\"search-result-import-path\">axis3d/src/light/ambient.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/box.js~boxgeometry",
    "class/src/geometry/box.js~BoxGeometry.html",
    "<span>BoxGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/box.js</span>",
    "class"
  ],
  [
    "axis3d/src/camera.js~cameracommand",
    "class/src/camera.js~CameraCommand.html",
    "<span>CameraCommand</span> <span class=\"search-result-import-path\">axis3d/src/camera.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/capsule.js~capsulegeometry",
    "class/src/geometry/capsule.js~CapsuleGeometry.html",
    "<span>CapsuleGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/capsule.js</span>",
    "class"
  ],
  [
    "axis3d/src/command.js~command",
    "class/src/command.js~Command.html",
    "<span>Command</span> <span class=\"search-result-import-path\">axis3d/src/command.js</span>",
    "class"
  ],
  [
    "axis3d/src/context.js~context",
    "class/src/context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">axis3d/src/context.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/cylinder.js~cylindergeometry",
    "class/src/geometry/cylinder.js~CylinderGeometry.html",
    "<span>CylinderGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/cylinder.js</span>",
    "class"
  ],
  [
    "axis3d/src/camera.js~default_camera_far",
    "variable/index.html#static-variable-DEFAULT_CAMERA_FAR",
    "<span>DEFAULT_CAMERA_FAR</span> <span class=\"search-result-import-path\">axis3d/src/camera.js</span>",
    "variable"
  ],
  [
    "axis3d/src/camera.js~default_camera_field_of_view",
    "variable/index.html#static-variable-DEFAULT_CAMERA_FIELD_OF_VIEW",
    "<span>DEFAULT_CAMERA_FIELD_OF_VIEW</span> <span class=\"search-result-import-path\">axis3d/src/camera.js</span>",
    "variable"
  ],
  [
    "axis3d/src/camera.js~default_camera_near",
    "variable/index.html#static-variable-DEFAULT_CAMERA_NEAR",
    "<span>DEFAULT_CAMERA_NEAR</span> <span class=\"search-result-import-path\">axis3d/src/camera.js</span>",
    "variable"
  ],
  [
    "axis3d/src/camera.js~default_camera_orientation_origin",
    "variable/index.html#static-variable-DEFAULT_CAMERA_ORIENTATION_ORIGIN",
    "<span>DEFAULT_CAMERA_ORIENTATION_ORIGIN</span> <span class=\"search-result-import-path\">axis3d/src/camera.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/types.js~directionallight",
    "variable/index.html#static-variable-DirectionalLight",
    "<span>DirectionalLight</span> <span class=\"search-result-import-path\">axis3d/src/light/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/directional.js~directionallightcommand",
    "class/src/light/directional.js~DirectionalLightCommand.html",
    "<span>DirectionalLightCommand</span> <span class=\"search-result-import-path\">axis3d/src/light/directional.js</span>",
    "class"
  ],
  [
    "axis3d/src/math/euler.js~euler",
    "class/src/math/euler.js~Euler.html",
    "<span>Euler</span> <span class=\"search-result-import-path\">axis3d/src/math/euler.js</span>",
    "class"
  ],
  [
    "axis3d/src/material/types.js~flatmaterial",
    "variable/index.html#static-variable-FlatMaterial",
    "<span>FlatMaterial</span> <span class=\"search-result-import-path\">axis3d/src/material/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/material/flat.js~flatmaterialcommand",
    "class/src/material/flat.js~FlatMaterialCommand.html",
    "<span>FlatMaterialCommand</span> <span class=\"search-result-import-path\">axis3d/src/material/flat.js</span>",
    "class"
  ],
  [
    "axis3d/src/frame.js~framecommand",
    "class/src/frame.js~FrameCommand.html",
    "<span>FrameCommand</span> <span class=\"search-result-import-path\">axis3d/src/frame.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/geometry.js~geometry",
    "class/src/geometry/geometry.js~Geometry.html",
    "<span>Geometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/geometry.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry_buffer.js~geometrybuffercomand",
    "class/src/geometry_buffer.js~GeometryBufferComand.html",
    "<span>GeometryBufferComand</span> <span class=\"search-result-import-path\">axis3d/src/geometry_buffer.js</span>",
    "class"
  ],
  [
    "axis3d/src/input/keyboard.js~keyboardinputcommand",
    "class/src/input/keyboard.js~KeyboardInputCommand.html",
    "<span>KeyboardInputCommand</span> <span class=\"search-result-import-path\">axis3d/src/input/keyboard.js</span>",
    "class"
  ],
  [
    "axis3d/src/material/types.js~lambertmaterial",
    "variable/index.html#static-variable-LambertMaterial",
    "<span>LambertMaterial</span> <span class=\"search-result-import-path\">axis3d/src/material/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/material/lambert.js~lambertmaterialcommand",
    "class/src/material/lambert.js~LambertMaterialCommand.html",
    "<span>LambertMaterialCommand</span> <span class=\"search-result-import-path\">axis3d/src/material/lambert.js</span>",
    "class"
  ],
  [
    "axis3d/src/light/types.js~light",
    "variable/index.html#static-variable-Light",
    "<span>Light</span> <span class=\"search-result-import-path\">axis3d/src/light/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/light.js~lightcommand",
    "class/src/light/light.js~LightCommand.html",
    "<span>LightCommand</span> <span class=\"search-result-import-path\">axis3d/src/light/light.js</span>",
    "class"
  ],
  [
    "axis3d/src/lines.js~linescommand",
    "class/src/lines.js~LinesCommand.html",
    "<span>LinesCommand</span> <span class=\"search-result-import-path\">axis3d/src/lines.js</span>",
    "class"
  ],
  [
    "axis3d/src/material/types.js~material",
    "variable/index.html#static-variable-Material",
    "<span>Material</span> <span class=\"search-result-import-path\">axis3d/src/material/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/material/material.js~materialcommand",
    "class/src/material/material.js~MaterialCommand.html",
    "<span>MaterialCommand</span> <span class=\"search-result-import-path\">axis3d/src/material/material.js</span>",
    "class"
  ],
  [
    "axis3d/src/mesh.js~meshcommand",
    "class/src/mesh.js~MeshCommand.html",
    "<span>MeshCommand</span> <span class=\"search-result-import-path\">axis3d/src/mesh.js</span>",
    "class"
  ],
  [
    "axis3d/src/input/mouse.js~mouseinputcommand",
    "class/src/input/mouse.js~MouseInputCommand.html",
    "<span>MouseInputCommand</span> <span class=\"search-result-import-path\">axis3d/src/input/mouse.js</span>",
    "class"
  ],
  [
    "axis3d/src/object3d.js~object3dcommand",
    "class/src/object3d.js~Object3DCommand.html",
    "<span>Object3DCommand</span> <span class=\"search-result-import-path\">axis3d/src/object3d.js</span>",
    "class"
  ],
  [
    "axis3d/src/input/orientation.js~orientationinputcommand",
    "class/src/input/orientation.js~OrientationInputCommand.html",
    "<span>OrientationInputCommand</span> <span class=\"search-result-import-path\">axis3d/src/input/orientation.js</span>",
    "class"
  ],
  [
    "axis3d/src/material/types.js~phongmaterial",
    "variable/index.html#static-variable-PhongMaterial",
    "<span>PhongMaterial</span> <span class=\"search-result-import-path\">axis3d/src/material/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/material/phong.js~phongmaterialcommand",
    "class/src/material/phong.js~PhongMaterialCommand.html",
    "<span>PhongMaterialCommand</span> <span class=\"search-result-import-path\">axis3d/src/material/phong.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/plane.js~planegeometry",
    "class/src/geometry/plane.js~PlaneGeometry.html",
    "<span>PlaneGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/plane.js</span>",
    "class"
  ],
  [
    "axis3d/src/light/types.js~pointlight",
    "variable/index.html#static-variable-PointLight",
    "<span>PointLight</span> <span class=\"search-result-import-path\">axis3d/src/light/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/point.js~pointlightcommand",
    "class/src/light/point.js~PointLightCommand.html",
    "<span>PointLightCommand</span> <span class=\"search-result-import-path\">axis3d/src/light/point.js</span>",
    "class"
  ],
  [
    "axis3d/src/math/quaternion.js~quaternion",
    "class/src/math/quaternion.js~Quaternion.html",
    "<span>Quaternion</span> <span class=\"search-result-import-path\">axis3d/src/math/quaternion.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/sphere.js~spheregeometry",
    "class/src/geometry/sphere.js~SphereGeometry.html",
    "<span>SphereGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/sphere.js</span>",
    "class"
  ],
  [
    "axis3d/src/light/types.js~spotlight",
    "variable/index.html#static-variable-SpotLight",
    "<span>SpotLight</span> <span class=\"search-result-import-path\">axis3d/src/light/types.js</span>",
    "variable"
  ],
  [
    "axis3d/src/stats.js~stat",
    "class/src/stats.js~Stat.html",
    "<span>Stat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "class"
  ],
  [
    "axis3d/src/texture.js~texturecommand",
    "class/src/texture.js~TextureCommand.html",
    "<span>TextureCommand</span> <span class=\"search-result-import-path\">axis3d/src/texture.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/torus.js~torusgeometry",
    "class/src/geometry/torus.js~TorusGeometry.html",
    "<span>TorusGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/torus.js</span>",
    "class"
  ],
  [
    "axis3d/src/input/touch.js~touchinputcommand",
    "class/src/input/touch.js~TouchInputCommand.html",
    "<span>TouchInputCommand</span> <span class=\"search-result-import-path\">axis3d/src/input/touch.js</span>",
    "class"
  ],
  [
    "axis3d/src/geometry/triangle.js~trianglegeometry",
    "class/src/geometry/triangle.js~TriangleGeometry.html",
    "<span>TriangleGeometry</span> <span class=\"search-result-import-path\">axis3d/src/geometry/triangle.js</span>",
    "class"
  ],
  [
    "axis3d/src/math/vector.js~vector",
    "class/src/math/vector.js~Vector.html",
    "<span>Vector</span> <span class=\"search-result-import-path\">axis3d/src/math/vector.js</span>",
    "class"
  ],
  [
    "axis3d/src/utils.js~clamptomaxsize",
    "function/index.html#static-function-clampToMaxSize",
    "<span>clampToMaxSize</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/math/quaternion.js~computeeuler",
    "function/index.html#static-function-computeEuler",
    "<span>computeEuler</span> <span class=\"search-result-import-path\">axis3d/src/math/quaternion.js</span>",
    "function"
  ],
  [
    "axis3d/src/math/euler.js~computequaternion",
    "function/index.html#static-function-computeQuaternion",
    "<span>computeQuaternion</span> <span class=\"search-result-import-path\">axis3d/src/math/euler.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~createcanvas",
    "function/index.html#static-function-createCanvas",
    "<span>createCanvas</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/stats.js~createstatlist",
    "function/index.html#static-function-createStatList",
    "<span>createStatList</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~debug",
    "variable/index.html#static-variable-debug",
    "<span>debug</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "variable"
  ],
  [
    "axis3d/src/stats.js~decrementstat",
    "function/index.html#static-function-decrementStat",
    "<span>decrementStat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "axis3d/src/context.js~defaults",
    "variable/index.html#static-variable-defaults",
    "<span>defaults</span> <span class=\"search-result-import-path\">axis3d/src/context.js</span>",
    "variable"
  ],
  [
    "axis3d/src/utils.js~define",
    "function/index.html#static-function-define",
    "<span>define</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~getscreenorientation",
    "function/index.html#static-function-getScreenOrientation",
    "<span>getScreenOrientation</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/stats.js~headstat",
    "function/index.html#static-function-headStat",
    "<span>headStat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "axis3d/src/stats.js~incrementstat",
    "function/index.html#static-function-incrementStat",
    "<span>incrementStat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~isdomelementinviewport",
    "function/index.html#static-function-isDOMElementInViewport",
    "<span>isDOMElementInViewport</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/light/ambient.js~kmaxambientlights",
    "variable/index.html#static-variable-kMaxAmbientLights",
    "<span>kMaxAmbientLights</span> <span class=\"search-result-import-path\">axis3d/src/light/ambient.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/directional.js~kmaxdirectionallights",
    "variable/index.html#static-variable-kMaxDirectionalLights",
    "<span>kMaxDirectionalLights</span> <span class=\"search-result-import-path\">axis3d/src/light/directional.js</span>",
    "variable"
  ],
  [
    "axis3d/src/light/point.js~kmaxpointlights",
    "variable/index.html#static-variable-kMaxPointLights",
    "<span>kMaxPointLights</span> <span class=\"search-result-import-path\">axis3d/src/light/point.js</span>",
    "variable"
  ],
  [
    "axis3d/src/utils.js~lerp",
    "function/index.html#static-function-lerp",
    "<span>lerp</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~makepoweroftwo",
    "function/index.html#static-function-makePowerOfTwo",
    "<span>makePowerOfTwo</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~nearestpoweroftwo",
    "function/index.html#static-function-nearestPowerOfTwo",
    "<span>nearestPowerOfTwo</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~radians",
    "function/index.html#static-function-radians",
    "<span>radians</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/stats.js~registerstat",
    "function/index.html#static-function-registerStat",
    "<span>registerStat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "axis3d/src/stats.js~resetstat",
    "function/index.html#static-function-resetStat",
    "<span>resetStat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "axis3d/src/utils.js~scalewithcanvas",
    "function/index.html#static-function-scaleWithCanvas",
    "<span>scaleWithCanvas</span> <span class=\"search-result-import-path\">axis3d/src/utils.js</span>",
    "function"
  ],
  [
    "axis3d/src/stats.js~stats",
    "variable/index.html#static-variable-stats",
    "<span>stats</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "variable"
  ],
  [
    "axis3d/src/stats.js~tailstat",
    "function/index.html#static-function-tailStat",
    "<span>tailStat</span> <span class=\"search-result-import-path\">axis3d/src/stats.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/camera.js",
    "file/src/camera.js.html",
    "src/camera.js",
    "file"
  ],
  [
    "src/camera.js~cameracommand#constructor",
    "class/src/camera.js~CameraCommand.html#instance-constructor-constructor",
    "src/camera.js~CameraCommand#constructor",
    "method"
  ],
  [
    "src/command.js",
    "file/src/command.js.html",
    "src/command.js",
    "file"
  ],
  [
    "src/command.js~command#constructor",
    "class/src/command.js~Command.html#instance-constructor-constructor",
    "src/command.js~Command#constructor",
    "method"
  ],
  [
    "src/context.js",
    "file/src/context.js.html",
    "src/context.js",
    "file"
  ],
  [
    "src/context.js~context#blur",
    "class/src/context.js~Context.html#instance-method-blur",
    "src/context.js~Context#blur",
    "method"
  ],
  [
    "src/context.js~context#caller",
    "class/src/context.js~Context.html#instance-get-caller",
    "src/context.js~Context#caller",
    "member"
  ],
  [
    "src/context.js~context#clear",
    "class/src/context.js~Context.html#instance-method-clear",
    "src/context.js~Context#clear",
    "method"
  ],
  [
    "src/context.js~context#constructor",
    "class/src/context.js~Context.html#instance-constructor-constructor",
    "src/context.js~Context#constructor",
    "method"
  ],
  [
    "src/context.js~context#depth",
    "class/src/context.js~Context.html#instance-get-depth",
    "src/context.js~Context#depth",
    "member"
  ],
  [
    "src/context.js~context#destroy",
    "class/src/context.js~Context.html#instance-method-destroy",
    "src/context.js~Context#destroy",
    "method"
  ],
  [
    "src/context.js~context#domelement",
    "class/src/context.js~Context.html#instance-get-domElement",
    "src/context.js~Context#domElement",
    "member"
  ],
  [
    "src/context.js~context#focus",
    "class/src/context.js~Context.html#instance-method-focus",
    "src/context.js~Context#focus",
    "method"
  ],
  [
    "src/context.js~context#hasfocus",
    "class/src/context.js~Context.html#instance-get-hasFocus",
    "src/context.js~Context#hasFocus",
    "member"
  ],
  [
    "src/context.js~context#pop",
    "class/src/context.js~Context.html#instance-method-pop",
    "src/context.js~Context#pop",
    "method"
  ],
  [
    "src/context.js~context#push",
    "class/src/context.js~Context.html#instance-method-push",
    "src/context.js~Context#push",
    "method"
  ],
  [
    "src/context.js~context#regl",
    "class/src/context.js~Context.html#instance-get-regl",
    "src/context.js~Context#regl",
    "member"
  ],
  [
    "src/context.js~context#reglcontext",
    "class/src/context.js~Context.html#instance-get-reglContext",
    "src/context.js~Context#reglContext",
    "member"
  ],
  [
    "src/context.js~context#reset",
    "class/src/context.js~Context.html#instance-method-reset",
    "src/context.js~Context#reset",
    "method"
  ],
  [
    "src/context.js~context#scope",
    "class/src/context.js~Context.html#instance-get-scope",
    "src/context.js~Context#scope",
    "member"
  ],
  [
    "src/context.js~context#stack",
    "class/src/context.js~Context.html#instance-get-stack",
    "src/context.js~Context#stack",
    "member"
  ],
  [
    "src/context.js~context#update",
    "class/src/context.js~Context.html#instance-method-update",
    "src/context.js~Context#update",
    "method"
  ],
  [
    "src/frame.js",
    "file/src/frame.js.html",
    "src/frame.js",
    "file"
  ],
  [
    "src/frame.js~framecommand#constructor",
    "class/src/frame.js~FrameCommand.html#instance-constructor-constructor",
    "src/frame.js~FrameCommand#constructor",
    "method"
  ],
  [
    "src/geometry/box.js",
    "file/src/geometry/box.js.html",
    "src/geometry/box.js",
    "file"
  ],
  [
    "src/geometry/box.js~boxgeometry#constructor",
    "class/src/geometry/box.js~BoxGeometry.html#instance-constructor-constructor",
    "src/geometry/box.js~BoxGeometry#constructor",
    "method"
  ],
  [
    "src/geometry/capsule.js",
    "file/src/geometry/capsule.js.html",
    "src/geometry/capsule.js",
    "file"
  ],
  [
    "src/geometry/capsule.js~capsulegeometry#constructor",
    "class/src/geometry/capsule.js~CapsuleGeometry.html#instance-constructor-constructor",
    "src/geometry/capsule.js~CapsuleGeometry#constructor",
    "method"
  ],
  [
    "src/geometry/cylinder.js",
    "file/src/geometry/cylinder.js.html",
    "src/geometry/cylinder.js",
    "file"
  ],
  [
    "src/geometry/cylinder.js~cylindergeometry#constructor",
    "class/src/geometry/cylinder.js~CylinderGeometry.html#instance-constructor-constructor",
    "src/geometry/cylinder.js~CylinderGeometry#constructor",
    "method"
  ],
  [
    "src/geometry/geometry.js",
    "file/src/geometry/geometry.js.html",
    "src/geometry/geometry.js",
    "file"
  ],
  [
    "src/geometry/geometry.js~geometry#cells",
    "class/src/geometry/geometry.js~Geometry.html#instance-get-cells",
    "src/geometry/geometry.js~Geometry#cells",
    "member"
  ],
  [
    "src/geometry/geometry.js~geometry#complex",
    "class/src/geometry/geometry.js~Geometry.html#instance-member-complex",
    "src/geometry/geometry.js~Geometry#complex",
    "member"
  ],
  [
    "src/geometry/geometry.js~geometry#constructor",
    "class/src/geometry/geometry.js~Geometry.html#instance-constructor-constructor",
    "src/geometry/geometry.js~Geometry#constructor",
    "method"
  ],
  [
    "src/geometry/geometry.js~geometry#normals",
    "class/src/geometry/geometry.js~Geometry.html#instance-get-normals",
    "src/geometry/geometry.js~Geometry#normals",
    "member"
  ],
  [
    "src/geometry/geometry.js~geometry#positions",
    "class/src/geometry/geometry.js~Geometry.html#instance-get-positions",
    "src/geometry/geometry.js~Geometry#positions",
    "member"
  ],
  [
    "src/geometry/geometry.js~geometry#uvs",
    "class/src/geometry/geometry.js~Geometry.html#instance-get-uvs",
    "src/geometry/geometry.js~Geometry#uvs",
    "member"
  ],
  [
    "src/geometry/index.js",
    "file/src/geometry/index.js.html",
    "src/geometry/index.js",
    "file"
  ],
  [
    "src/geometry/plane.js",
    "file/src/geometry/plane.js.html",
    "src/geometry/plane.js",
    "file"
  ],
  [
    "src/geometry/plane.js~planegeometry#constructor",
    "class/src/geometry/plane.js~PlaneGeometry.html#instance-constructor-constructor",
    "src/geometry/plane.js~PlaneGeometry#constructor",
    "method"
  ],
  [
    "src/geometry/sphere.js",
    "file/src/geometry/sphere.js.html",
    "src/geometry/sphere.js",
    "file"
  ],
  [
    "src/geometry/sphere.js~spheregeometry#constructor",
    "class/src/geometry/sphere.js~SphereGeometry.html#instance-constructor-constructor",
    "src/geometry/sphere.js~SphereGeometry#constructor",
    "method"
  ],
  [
    "src/geometry/torus.js",
    "file/src/geometry/torus.js.html",
    "src/geometry/torus.js",
    "file"
  ],
  [
    "src/geometry/torus.js~torusgeometry#constructor",
    "class/src/geometry/torus.js~TorusGeometry.html#instance-constructor-constructor",
    "src/geometry/torus.js~TorusGeometry#constructor",
    "method"
  ],
  [
    "src/geometry/triangle.js",
    "file/src/geometry/triangle.js.html",
    "src/geometry/triangle.js",
    "file"
  ],
  [
    "src/geometry/triangle.js~trianglegeometry#constructor",
    "class/src/geometry/triangle.js~TriangleGeometry.html#instance-constructor-constructor",
    "src/geometry/triangle.js~TriangleGeometry#constructor",
    "method"
  ],
  [
    "src/geometry_buffer.js",
    "file/src/geometry_buffer.js.html",
    "src/geometry_buffer.js",
    "file"
  ],
  [
    "src/geometry_buffer.js~geometrybuffercomand#constructor",
    "class/src/geometry_buffer.js~GeometryBufferComand.html#instance-constructor-constructor",
    "src/geometry_buffer.js~GeometryBufferComand#constructor",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/input/index.js",
    "file/src/input/index.js.html",
    "src/input/index.js",
    "file"
  ],
  [
    "src/input/keyboard.js",
    "file/src/input/keyboard.js.html",
    "src/input/keyboard.js",
    "file"
  ],
  [
    "src/input/keyboard.js~keyboardinputcommand#constructor",
    "class/src/input/keyboard.js~KeyboardInputCommand.html#instance-constructor-constructor",
    "src/input/keyboard.js~KeyboardInputCommand#constructor",
    "method"
  ],
  [
    "src/input/mouse.js",
    "file/src/input/mouse.js.html",
    "src/input/mouse.js",
    "file"
  ],
  [
    "src/input/mouse.js~mouseinputcommand#constructor",
    "class/src/input/mouse.js~MouseInputCommand.html#instance-constructor-constructor",
    "src/input/mouse.js~MouseInputCommand#constructor",
    "method"
  ],
  [
    "src/input/orientation.js",
    "file/src/input/orientation.js.html",
    "src/input/orientation.js",
    "file"
  ],
  [
    "src/input/orientation.js~orientationinputcommand#constructor",
    "class/src/input/orientation.js~OrientationInputCommand.html#instance-constructor-constructor",
    "src/input/orientation.js~OrientationInputCommand#constructor",
    "method"
  ],
  [
    "src/input/touch.js",
    "file/src/input/touch.js.html",
    "src/input/touch.js",
    "file"
  ],
  [
    "src/input/touch.js~touchinputcommand#constructor",
    "class/src/input/touch.js~TouchInputCommand.html#instance-constructor-constructor",
    "src/input/touch.js~TouchInputCommand#constructor",
    "method"
  ],
  [
    "src/light/ambient.js",
    "file/src/light/ambient.js.html",
    "src/light/ambient.js",
    "file"
  ],
  [
    "src/light/ambient.js~ambientlightcommand#constructor",
    "class/src/light/ambient.js~AmbientLightCommand.html#instance-constructor-constructor",
    "src/light/ambient.js~AmbientLightCommand#constructor",
    "method"
  ],
  [
    "src/light/directional.js",
    "file/src/light/directional.js.html",
    "src/light/directional.js",
    "file"
  ],
  [
    "src/light/directional.js~directionallightcommand#constructor",
    "class/src/light/directional.js~DirectionalLightCommand.html#instance-constructor-constructor",
    "src/light/directional.js~DirectionalLightCommand#constructor",
    "method"
  ],
  [
    "src/light/index.js",
    "file/src/light/index.js.html",
    "src/light/index.js",
    "file"
  ],
  [
    "src/light/light.js",
    "file/src/light/light.js.html",
    "src/light/light.js",
    "file"
  ],
  [
    "src/light/light.js~lightcommand#constructor",
    "class/src/light/light.js~LightCommand.html#instance-constructor-constructor",
    "src/light/light.js~LightCommand#constructor",
    "method"
  ],
  [
    "src/light/point.js",
    "file/src/light/point.js.html",
    "src/light/point.js",
    "file"
  ],
  [
    "src/light/point.js~pointlightcommand#constructor",
    "class/src/light/point.js~PointLightCommand.html#instance-constructor-constructor",
    "src/light/point.js~PointLightCommand#constructor",
    "method"
  ],
  [
    "src/light/types.js",
    "file/src/light/types.js.html",
    "src/light/types.js",
    "file"
  ],
  [
    "src/lines.js",
    "file/src/lines.js.html",
    "src/lines.js",
    "file"
  ],
  [
    "src/lines.js~linescommand#constructor",
    "class/src/lines.js~LinesCommand.html#instance-constructor-constructor",
    "src/lines.js~LinesCommand#constructor",
    "method"
  ],
  [
    "src/material/flat.js",
    "file/src/material/flat.js.html",
    "src/material/flat.js",
    "file"
  ],
  [
    "src/material/flat.js~flatmaterialcommand#constructor",
    "class/src/material/flat.js~FlatMaterialCommand.html#instance-constructor-constructor",
    "src/material/flat.js~FlatMaterialCommand#constructor",
    "method"
  ],
  [
    "src/material/index.js",
    "file/src/material/index.js.html",
    "src/material/index.js",
    "file"
  ],
  [
    "src/material/lambert.js",
    "file/src/material/lambert.js.html",
    "src/material/lambert.js",
    "file"
  ],
  [
    "src/material/lambert.js~lambertmaterialcommand#constructor",
    "class/src/material/lambert.js~LambertMaterialCommand.html#instance-constructor-constructor",
    "src/material/lambert.js~LambertMaterialCommand#constructor",
    "method"
  ],
  [
    "src/material/material.js",
    "file/src/material/material.js.html",
    "src/material/material.js",
    "file"
  ],
  [
    "src/material/material.js~materialcommand#constructor",
    "class/src/material/material.js~MaterialCommand.html#instance-constructor-constructor",
    "src/material/material.js~MaterialCommand#constructor",
    "method"
  ],
  [
    "src/material/phong.js",
    "file/src/material/phong.js.html",
    "src/material/phong.js",
    "file"
  ],
  [
    "src/material/phong.js~phongmaterialcommand#constructor",
    "class/src/material/phong.js~PhongMaterialCommand.html#instance-constructor-constructor",
    "src/material/phong.js~PhongMaterialCommand#constructor",
    "method"
  ],
  [
    "src/material/types.js",
    "file/src/material/types.js.html",
    "src/material/types.js",
    "file"
  ],
  [
    "src/math/euler.js",
    "file/src/math/euler.js.html",
    "src/math/euler.js",
    "file"
  ],
  [
    "src/math/euler.js~euler#constructor",
    "class/src/math/euler.js~Euler.html#instance-constructor-constructor",
    "src/math/euler.js~Euler#constructor",
    "method"
  ],
  [
    "src/math/euler.js~euler#order",
    "class/src/math/euler.js~Euler.html#instance-member-order",
    "src/math/euler.js~Euler#order",
    "member"
  ],
  [
    "src/math/index.js",
    "file/src/math/index.js.html",
    "src/math/index.js",
    "file"
  ],
  [
    "src/math/quaternion.js",
    "file/src/math/quaternion.js.html",
    "src/math/quaternion.js",
    "file"
  ],
  [
    "src/math/quaternion.js~quaternion#constructor",
    "class/src/math/quaternion.js~Quaternion.html#instance-constructor-constructor",
    "src/math/quaternion.js~Quaternion#constructor",
    "method"
  ],
  [
    "src/math/vector.js",
    "file/src/math/vector.js.html",
    "src/math/vector.js",
    "file"
  ],
  [
    "src/math/vector.js~vector#[symbol.iterator]",
    "class/src/math/vector.js~Vector.html#instance-method-[Symbol.iterator]",
    "src/math/vector.js~Vector#[Symbol.iterator]",
    "method"
  ],
  [
    "src/math/vector.js~vector#componentlength",
    "class/src/math/vector.js~Vector.html#instance-get-componentLength",
    "src/math/vector.js~Vector#componentLength",
    "member"
  ],
  [
    "src/math/vector.js~vector#constructor",
    "class/src/math/vector.js~Vector.html#instance-constructor-constructor",
    "src/math/vector.js~Vector#constructor",
    "method"
  ],
  [
    "src/math/vector.js~vector#length",
    "class/src/math/vector.js~Vector.html#instance-get-length",
    "src/math/vector.js~Vector#length",
    "member"
  ],
  [
    "src/math/vector.js~vector#ref",
    "class/src/math/vector.js~Vector.html#instance-get-ref",
    "src/math/vector.js~Vector#ref",
    "member"
  ],
  [
    "src/math/vector.js~vector#set",
    "class/src/math/vector.js~Vector.html#instance-method-set",
    "src/math/vector.js~Vector#set",
    "method"
  ],
  [
    "src/math/vector.js~vector#toarray",
    "class/src/math/vector.js~Vector.html#instance-method-toArray",
    "src/math/vector.js~Vector#toArray",
    "method"
  ],
  [
    "src/math/vector.js~vector#tojson",
    "class/src/math/vector.js~Vector.html#instance-method-toJSON",
    "src/math/vector.js~Vector#toJSON",
    "method"
  ],
  [
    "src/math/vector.js~vector#valueof",
    "class/src/math/vector.js~Vector.html#instance-method-valueOf",
    "src/math/vector.js~Vector#valueOf",
    "method"
  ],
  [
    "src/mesh.js",
    "file/src/mesh.js.html",
    "src/mesh.js",
    "file"
  ],
  [
    "src/mesh.js~meshcommand#constructor",
    "class/src/mesh.js~MeshCommand.html#instance-constructor-constructor",
    "src/mesh.js~MeshCommand#constructor",
    "method"
  ],
  [
    "src/object3d.js",
    "file/src/object3d.js.html",
    "src/object3d.js",
    "file"
  ],
  [
    "src/object3d.js~object3dcommand#constructor",
    "class/src/object3d.js~Object3DCommand.html#instance-constructor-constructor",
    "src/object3d.js~Object3DCommand#constructor",
    "method"
  ],
  [
    "src/object3d.js~object3dcommand.id",
    "class/src/object3d.js~Object3DCommand.html#static-method-id",
    "src/object3d.js~Object3DCommand.id",
    "method"
  ],
  [
    "src/stats.js",
    "file/src/stats.js.html",
    "src/stats.js",
    "file"
  ],
  [
    "src/stats.js~stat#constructor",
    "class/src/stats.js~Stat.html#instance-constructor-constructor",
    "src/stats.js~Stat#constructor",
    "method"
  ],
  [
    "src/stats.js~stat#info",
    "class/src/stats.js~Stat.html#instance-member-info",
    "src/stats.js~Stat#info",
    "member"
  ],
  [
    "src/stats.js~stat#name",
    "class/src/stats.js~Stat.html#instance-member-name",
    "src/stats.js~Stat#name",
    "member"
  ],
  [
    "src/stats.js~stat#timestamp",
    "class/src/stats.js~Stat.html#instance-member-timestamp",
    "src/stats.js~Stat#timestamp",
    "member"
  ],
  [
    "src/texture.js",
    "file/src/texture.js.html",
    "src/texture.js",
    "file"
  ],
  [
    "src/texture.js~texturecommand#constructor",
    "class/src/texture.js~TextureCommand.html#instance-constructor-constructor",
    "src/texture.js~TextureCommand#constructor",
    "method"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]